# Generated by Django 3.0.3 on 2020-07-18 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20200713_0206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='technology',
            new_name='description2',
        ),
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='work',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
